### ISSUE TITLE
Issue with auto_driver.py and mission_commands.py

### ISSUE THREAD

**Issue by mxdrew** [amichael1227/ROSPerch#3]
When using `rosrun rosperch mission_commands.py` I get the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/catkin_ws/src/rosperch/scripts/wip/mission_commands.py", line 43, in <module>
    t = threading.Thread(target=listener,args=queue,daemon=True).start
NameError: name 'queue' is not defined
```
And when I run `rosrun rosperch auto_driver.py` I get  this error:
  
```
File "/home/ubuntu/catkin_ws/src/rosperch/scripts/wip/auto_driver.py", line 69
    while (curr_time - start_time) < t
                                     ^
SyntaxError: invalid syntax
```

**Comment by john-mclinden** [comment]
Resolved these issues by editing auto_driver.py and mission_commands.py, along with several other issues.
